services:
  web:
    image: ghcr.io/thezion-club/thezion-club:latest
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./:/www/
      - /etc/ssl:/etc/ssl:ro
    environment:
      - docker=true
    depends_on:
      - redis
    network_mode: host
    command: php artisan octane:start --host=127.0.0.1 --port=13000
    restart: always
  horizon:
    image: ghcr.io/thezion-club/thezion-club:latest
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./:/www/
      - /etc/ssl:/etc/ssl:ro
    restart: always
    network_mode: host
    command: php artisan horizon
    depends_on:
      - redis
  redis:
    image: redis:8-alpine
    command: redis-server --unixsocket /data/redis.sock --unixsocketperm 777
    restart: unless-stopped
    volumes:
      - ./.docker/.data/redis:/data
    sysctls:
      net.core.somaxconn: 1024
